name: susox
favicon: null
layout_spectrum: 0.9518183732870966
typography_spectrum: 0.589536223327741
title: susox
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#e8e8e8'
    - '#00505b'
    - '#06f8d6'
    - '#70cdbc'
  brandStrength: 0.8125
  lightness: 0.39526333613321185
  saturation: 0.5485050799325109
  rhythmicContrast: 0.712415132438764
purpose: []
